#!/bin/bash

PORT="1234"

while true
do
    mono OpenRA.Game.exe Game.Mods=ra Server.Name=_openra_ Server.ListenPort=`echo $PORT` Server.ExternalPort=`echo $PORT` --headless --headless-no-config
    sleep 5
done
